# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# compile CXX with /usr/bin/c++
CXX_DEFINES = -Dlivox_lidar_sdk_shared_EXPORTS

CXX_INCLUDES = -I/home/aria/slam_ws/Livox-SDK2/sdk_core/../include -I/home/aria/slam_ws/Livox-SDK2/sdk_core/../3rdparty -I/home/aria/slam_ws/Livox-SDK2/sdk_core/../3rdparty/spdlog -I/home/aria/slam_ws/Livox-SDK2/sdk_core/.

CXX_FLAGS =  -pthread -std=gnu++11 -fPIC -Wall

